apiVersion: v1
kind: Pod
metadata:
  name: custom-attacker
  labels:
    app: custom-attacker
spec:
  containers:
  - name: app
    image: <your-dockerhub-username>/custom-test:latest
    imagePullPolicy: Always